[package]
name = "rust-reverse-shell-system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"]}
warp = "0.3"
futures-util = "0.3"
self_update = "0.39.0"
